on:
  push:
    branches:
      - main
name: Tag & Publish
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for changelog generation
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com
          scope: "@infraregistry"
      - name: Install tygo
        run: go install github.com/gzuidhof/tygo@latest
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: main
          commit-message: "CI: bumps version to {{version}} [skip ci]"
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate types
        run: make types
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
